import type { KnowledgeChunk } from "./types.js";

/** Conteúdo clínico aprofundado para público de odontologia. */
export const CLINICAL_EXTRA: KnowledgeChunk[] = [
  {
    id: "endo-pulpite",
    title: "Pulpite reversível vs irreversível",
    tags: ["pulpite", "endodontia", "polpa", "dor", "vitalidade", "canal"],
    body: `Pulpite reversível: dor provocada (frio/doce), breve, sem dor espontânea persistente — manejo pode ser conservador (remover causa, proteção pulpar) conforme quadro. Pulpite irreversível: dor espontânea, prolongada, noturna, difícil de localizar; frequentemente indica tratamento endodôntico. Necrose: ausência de resposta vital; pode evoluir para periodontite apical. Diagnóstico exige exame clínico + testes + imagem — não feche só por chat.`,
    audience: "pro",
  },
  {
    id: "endo-acesso-irrigacao",
    title: "Acesso, instrumentação e irrigação endodôntica",
    tags: ["endodontia", "acesso", "instrumentação", "instrumentacao", "irrigação", "irrigacao", "hipoclorito", "lima"],
    body: `Fluxo didático: diagnóstico → anestesia → isolamento absoluto → acesso coronário → localização de canais → patência → instrumentação (manual/rotatória) com irrigação abundante → medicação intracanal se indicada → obturação → selamento coronário. Hipoclorito de sódio é irrigante clássico (concentração e protocolo sob responsabilidade clínica). Comprimento de trabalho e anatomia do canal (principalmente molares) condicionam o sucesso.`,
    audience: "pro",
  },
  {
    id: "perio-estagios",
    title: "Periodontite — estágios e fatores",
    tags: ["periodontite", "periodontia", "estágio", "estagio", "bolsa", "perda", "inserção", "insercao"],
    body: `Periodontite envolve inflamação com perda de inserção clínica e osso. Classificações modernas usam estágios (extensão/severidade) e graus (risco/progressão). Sinais: sangramento, bolsa, mobilidade, retração, perda óssea radiográfica. Tratamento: higiene, raspagem/alisamento, controle de fatores (tabaco, diabetes), reavaliação; cirurgia em casos selecionados. Gengivite não tem perda de inserção — ponto-chave diferencial.`,
    audience: "pro",
  },
  {
    id: "dentistica-adesao",
    title: "Adesão e resina composta — princípios",
    tags: ["adesão", "adesao", "resina", "dentística", "dentistica", "ácido", "acido", "primer", "camada"],
    body: `Restauração adesiva depende de isolamento, preparo adequado, protocolo adesivo (condicionamento/adesivo conforme sistema) e inserção da resina em incrementos com fotopolimerização. Contorno proximal, ponto de contato e oclusão são tão críticos quanto a adesão. Polimento reduz biofilme e desgaste. Falhas comuns: contaminação por saliva, subpolimerização, excesso oclusal, contato aberto.`,
    audience: "pro",
  },
  {
    id: "black-classes",
    title: "Classes de Black (localização de cavidades)",
    tags: ["black", "classe", "classes", "cavidade", "preparo", "dentística", "dentistica"],
    body: `Classe I: fóssulas/sulcos oclusais (e equivalentes). II: proximal de posteriores. III: proximal de anteriores sem ângulo. IV: proximal de anteriores com ângulo incisal. V: terço cervical vestibular/lingual. VI: cúspides/bordas (uso variável). Hoje prioriza-se mínima invasão, mas as classes ainda organizam o raciocínio clínico e acadêmico.`,
    audience: "student",
  },
  {
    id: "orto-angle",
    title: "Classificação de Angle — Classes I, II e III",
    tags: ["angle", "ortodontia", "classe", "classe i", "classe ii", "classe iii", "molar", "canina"],
    body: `Angle descreve a relação sagital dos primeiros molares permanentes (e analogamente caninos). Classe I: cúspide MV do 1º molar superior oclui no sulco vestibular do 1º molar inferior (relação neutra). Classe II: molar superior mesializado em relação ao inferior (divisões 1 e 2 no superior). Classe III: molar superior distalizado / inferior mesializado. É ponto de partida — diagnóstico ortodôntico completo inclui face, cefalometria e modelos.`,
    audience: "pro",
  },
  {
    id: "rx-indicacoes",
    title: "Indicações de exames radiográficos",
    tags: ["radiografia", "periapical", "interproximal", "bitewing", "panorâmica", "panoramica", "alara", "cbct"],
    body: `Periapical: coroa, raiz e periápice (endo, trauma, lesões). Interproximal (bite-wing): cáries proximais e cristas ósseas. Panorâmica: visão ampla (sisos, anomalias, planejamento). CBCT: quando 2D é insuficiente (implantes, anatomia complexa, dentes retidos) — dose maior, indicação criteriosa (ALARA). Sempre correlacionar com exame clínico.`,
    audience: "pro",
  },
  {
    id: "anestesia-nai",
    title: "Bloqueio do nervo alveolar inferior — noções",
    tags: ["anestesia", "alveolar", "inferior", "bloqueio", "mandibular", "nai", "trigêmeo", "trigemeo"],
    body: `O bloqueio do NAI anestesia hemiarcada inferior (dentes, mucosa lingual parcial; vestibular molar pode exigir reforço). Referências anatômicas clássicas: plano oclusal, rafe pterigomandibular, língula. Riscos: hematoma, trismo, parestesia rara, falha técnica. Infiltração maxilar costuma bastar no superior por porosidade óssea. Somente profissional habilitado executa.`,
    audience: "pro",
  },
  {
    id: "cirurgia-siso",
    title: "Terceiros molares — avaliação cirúrgica",
    tags: ["siso", "terceiro", "molar", "exodontia", "cirurgia", "retido", "incluso"],
    body: `Indicação de remoção depende de patologia, risco de cárie/pericoronarite, ortodontia e posição. Avaliar proximidade do canal mandibular (inferiores) e seio (superiores) em imagem. Técnica: flap, osteotomia/odontosecção se preciso, luxação, remoção, irrigação, sutura. Orientar cuidados pós-operatórios e sinais de alerta (alveolite, infecção, parestesia).`,
    audience: "pro",
  },
  {
    id: "implante-planejamento",
    title: "Planejamento de implante — pontos-chave",
    tags: ["implante", "osseointegração", "osseointegracao", "cbct", "carga", "peri-implantar"],
    body: `Planejamento: anamnese, espaço protético, volume ósseo (CBCT), distância de nervos/seios, oclusão e higiene. Osseointegração é a ancoragem direta osso-implante. Carga imediata vs convencional depende de estabilidade primária e protocolo. Manutenção peri-implantar evita mucosite/peri-implantite. Sucesso = cirurgia + prótese + manutenção.`,
    audience: "pro",
  },
  {
    id: "farmaco-racional",
    title: "Uso racional de analgésicos e antibióticos",
    tags: ["analgésico", "analgesico", "aine", "antibiótico", "antibiotico", "farmacologia", "infecção", "infeccao"],
    body: `Dor odontogênica: manejo causal (drenagem, endo, remoção da causa) + analgesia. AINEs/analgésicos conforme histórico e contraindicações. Antibiótico não substitui intervenção local na maioria das infecções odontogênicas; reservar a celulite, imunocomprometidos e indicações selecionadas — combater resistência. A assistente não monta posologia.`,
    audience: "pro",
  },
  {
    id: "trauma-avulsao",
    title: "Trauma — avulsão de dente permanente",
    tags: ["trauma", "avulsão", "avulsao", "reimplante", "urgência", "urgencia"],
    body: `Avulsão de permanente: reimplantar o mais rápido possível se indicado; se não, conservar em leite, soro ou saliva (evitar seco). Não esfregar o ligamento. Buscar atendimento imediato para reimplante/contenção e acompanhamento endodôntico conforme guidelines. Decíduos: urgência presencial.`,
    audience: "pro",
  },
  {
    id: "oclusao-guias",
    title: "Guias oclusais e interferências",
    tags: ["oclusão", "oclusao", "guia", "canina", "grupo", "interferência", "interferencia", "cêntrica", "centrica"],
    body: `Contatos cêntricos estáveis distribuem carga. Guia canina: desoclusão dos posteriores em lateralidade pelo canino. Função de grupo: vários dentes guiam. Interferências oclusais (especialmente não trabalhadoras) podem gerar trauma oclusal, fratura e sintomas musculares. Em escultura/prótese, preservar morfologia que permita guias coerentes.`,
    audience: "pro",
  },
  {
    id: "histologia-jce",
    title: "JCE, esmalte e dentina na clínica",
    tags: ["jce", "esmalte", "dentina", "colo", "sensibilidade", "histologia"],
    body: `A junção cemento-esmalte (JCE) é marco periodontal e de preparos. Esmalte não se regenera; dentina responde com esclerose/terciária. Exposição dentinária → sensibilidade. Em periodontia e prótese, respeito ao espaço biológico e ao contorno cervical reduz inflamação.`,
    audience: "student",
  },
  {
    id: "protese-preparo",
    title: "Preparo protético — princípios",
    tags: ["prótese", "protese", "preparo", "coroa", "chanfro", "ombro", "retenção", "retencao"],
    body: `Preparo para coroa busca retenção/resistência, desgaste seletivo, término cervical nítido (chanfro/ombro conforme material) e preservação pulpopulpar quando possível. Provisório protege e mantém espaço. Moldagem/escaneamento de qualidade define adaptação. Anatomia oclusal e proximal da restauração final influencia periodonto e oclusão.`,
    audience: "pro",
  },
  {
    id: "odonto-ped-selante",
    title: "Selante e prevenção em odontopediatria",
    tags: ["selante", "odontopediatria", "criança", "crianca", "prevenção", "prevencao", "flúor", "fluor"],
    body: `Selantes oclusais reduzem cárie em sulcos profundos de molares permanentes (e às vezes decíduos). Flúor tópico e orientação de dieta/higiene são pilares. Manejo comportamental e consentimento dos responsáveis. Trauma e hábitos (chupeta, sucção) entram na avaliação da dentição em desenvolvimento.`,
    audience: "student",
  },
  {
    id: "estomato-alerta",
    title: "Lesões de mucosa — sinais de alerta",
    tags: ["estomatologia", "leucoplasia", "úlcera", "ulcera", "mucosa", "biópsia", "biopsia"],
    body: `Úlcera que não cicatriza em ~2 semanas, placas brancas/vermelhas persistentes, endurecimento ou linfonodomegalia merecem investigação. Fatores de risco: tabaco, álcool, HPV em alguns contextos. Aftas recorrentes são comuns, mas não assuma benignidade sem exame. Assistente educa — não diagnostica câncer.`,
    audience: "pro",
  },
  {
    id: "biosseg-ppe",
    title: "Cadeia de biossegurança",
    tags: ["biossegurança", "biosseguranca", "epi", "autoclave", "desinfecção", "desinfeccao"],
    body: `EPI, higienização das mãos, barreiras, desinfecção de superfícies, lavagem e esterilização (autoclave) com monitoramento, e descarte de perfurocortantes formam a base. Reduz infecção cruzada e protege equipe/paciente. Protocolos locais e vigilância sanitária devem ser seguidos.`,
    audience: "student",
  },
];
